### PR TITLE
Add Noam, add CZI funding

### PR DESCRIPTION
**Pull request by noamross**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Can we at least discuss such changes before making them?   How about

"The RP was created by C + D, and is now maintained by C, D + N."   ?

**Comment by noamross** [comment]
No problem, will update.

**Comment by cboettig** [comment]
my bad! thanks @eddelbuettel @noamross

**Comment by eddelbuettel** [comment]
No mas, and welcome aboard.  At first I was a little worried about CZI as I had not seen the announcement but there it is -- all good.

**Comment by noamross** [comment]
Glad to be here!

**Pull request merged**
