### PR TITLE
Use quarto extensions

### PR DESCRIPTION
**Pull request by eitsupi**
Install and use some quarto extensions.

- https://github.com/quarto-ext/fontawesome to use the Docker logo etc.
  image
  image
- https://github.com/quarto-ext/code-filename to display the file name to code blocks.
  image

### CODE REVIEW

**Comment by eitsupi** [comment]
`quarto render` failed by quarto-dev/quarto-cli#1361.

**Comment by cderv** [comment]
@eitsupi this should be solved in quarto `1.0.15`. Hopefully it will build correctly. 
Thank you for the feedback !

**Comment by eitsupi** [comment]
@cderv Yes, it now builds correctly. Thank you for the immediate fixes!

@cboettig Instead of deploying to Netlify, we can download the rendered results from a GitHub Actions run.
https://github.com/rocker-org/website/actions/runs/2660871974

**Comment by cderv** [comment]
Also just to share that we updated our action in `quarto-actions` and there is now a v2. 
No issue using the v1 but just wanted to share this as v2 has support for `quarto publish` 
https://github.com/quarto-dev/quarto-actions/

**Pull request merged**
