### PR TITLE
Add note about the `pak` package

### PR DESCRIPTION
**Pull request by eitsupi**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I should add something about [r2u](https://eddelbuettel.github.io/r2u/) which automates all that (if one works at the current 'head' rather than versioned / time-machined in the past).

**Comment by eitsupi** [comment]
> I should add something about [r2u](https://eddelbuettel.github.io/r2u/) which automates all that (if one works at the current 'head' rather than versioned / time-machined in the past).

Of course!
I opened this PR because I learned about the function of pak during my work in https://github.com/rocker-org/devcontainer-features/tree/main/src/r-rig, and I just wanted to write it down before I forget.

**Comment by eddelbuettel** [comment]
> if it were linked there

I meant a bit more.  I produce a set of containers r-ubuntu, r-bspm, ... and r2u currently sits on top of r-bspm and adds the new apt repo.  I think I should just inject the r2u logic into r-ubuntu and/or r-bspm.   There is no reason to use R on Ubuntu (20.04 or 22.04) without the added repo now adding at 18.5k packages (plus 0.3k BioC),

**Comment by eddelbuettel** [comment]
Actually _just documenting_ is easy.  Feel free to add a line (with the required disclaimer that it is not at all r-ver but only 'current', simply a different use case).

But it works just great. I switched all my CI to it, and it is effing fast.  Peter tweeted this yesterday (and we could shrink the size of r2u by not using the convenient bspm wrapper needing some Python):

image

(part of a thread starting at https://twitter.com/psolymos/status/1575151393589153793)

**Pull request merged**
