### PR TITLE
Initial Rocker Singularity documentation

### PR DESCRIPTION
**Pull request by nathanweeks**
Starting point for documentation on running Rocker using Singularity.

Lots of details could be added (e.g., the interactive commands run rserver in the foreground, and don't include cleaning up "orphan" rsession processes if they user doesn't shut them down via the rstudio web UI; maybe [Singularity container instances](http://singularity.lbl.gov/docs-instances) container instances could be used here).

### CODE REVIEW

**Comment by cboettig** [comment]
This looks very nice!  I'll merge now and then I should add it to the dropdown menu soon.

**Comment by paciorek** [comment]
@nathanweeks I was trying to use Rstudio server in Singularity on a system where I don't have root access and ran into the problem that Rstudio server wants to write to /var. Have you run into this? I think this would be a common problem.

**Comment by nathanweeks** [comment]
@paciorek : sorry for the slow response. Did RStudio error when attempting to write to /var/tmp, or another subdirectory of /var, and what was the specific error message?

**Comment by nathanweeks** [comment]
@paciorek: have you seen the the example SLURM job script in the Rocker [Singularity documentation](https://www.rocker-project.org/use/singularity/)? It illustrates the use of `singularity exec` to invoke rserver directly, and enforces authentication (using a pseudo-randomly generated password).

**Comment by paciorek** [comment]
Ah, thanks; I had missed that -- looks like the approach I ended up taking was essentially the same albeit via the runscript rather than singularity exec.

**Pull request merged**
