### PR TITLE
Update repo url of ubuntu-lts and bspm

### PR DESCRIPTION
**Pull request by eitsupi**
Related to rocker-org/rocker#495

### CODE REVIEW

**Review by eddelbuettel — APPROVED** [review]
:heart:

**Comment by eddelbuettel** [comment]
Thanks for catching this. I really need to clean up the hierarchy of containers and the little 'tree' with some (`r-base`) starting from Debian and some (leading _e.g._ to the wonderful r2u ones) off Ubuntu.

First order, though, is probably to bring r2u inside Rocker too.  I am currently serving 

```sh
edd@rob:~$ r2u.r count
29198 .deb files downloaded
edd@rob:~$ 
```

several thousand .deb files a day (logs reset Sunday morning, so these 29.2k are since then; this week is inflated as the 'turnitin dot com' service 'found them' and slurps them too, needlessly.

**Comment by eitsupi** [comment]
Documents are minimal at the moment and I would be happy for you to edit these, including directory changes.

**Comment by eddelbuettel** [comment]
Yes I need to clear in my head first how I think about it all...

**Pull request merged**
