### PR TITLE
Update shared_volumes.md

### PR DESCRIPTION
**Pull request by kscottz**
Add a better example

### CODE REVIEW

**Review by eitsupi — CHANGES_REQUESTED** [review]
Thanks for your contribution.

But I think this is too far from the containers used on this website so this is not an appropriate example.

- Why "tb4"?
- What is `/opt/ros/container_ws/src/`?

**Comment by kscottz** [comment]
> Why "tb4"?

Because that's the container I had in front of me.  I don't care what the name as long as someone points out, "this name is the container name."

> What is /opt/ros/container_ws/src/?

Because that's what I had in front of me. I would accept an arbitrary destination directory.  A good alternative might be `<directory_inside_container>`

If you land on this page from an arbitrary Google search you have no context about the conventions that are used.  It took me a good 30 to understand how to get file mounting to work correctly. I imagine most visitors to this page just want to know "How do I get this local directory to mount to a specific location within my container." I wrote an example of how to do that. All of the names are arbitrary but ROS like in nature because looking at ROS related questions led me here.

**Comment by eitsupi** [comment]
Thanks for the reply.

I don't think it is necessary to go into detail about Docker on this page that is not specific to the Rocker Project.
Links to the official Docker documentation already exist on this page, but it might be worth emphasizing that more.

**Comment by kscottz** [comment]
Oh my, you are correct. Sorry about the confusion.

**Pull request closed without merging**
