### PR TITLE
add side menu to use page

### PR DESCRIPTION
**Pull request by cboettig**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Is there a way to preview?

**Comment by cboettig** [comment]
@eddelbuettel Yes, I think you should be able to preview by clicking on the "Details" tab above where it says "All checks have passed" (the check is the preview-deploy success state for netlify).  It's possible I may need to add you to the netlify deploy first??

**Comment by eddelbuettel** [comment]
You may have too.  I see no link.  But I trust you on this and other issues :)

**Comment by cboettig** [comment]
ok, lemme know if you can see the preview here: https://deploy-preview-2--rocker.netlify.com/

**Comment by cboettig** [comment]
I see, when I'm logged in I get one of those "All checks have passed" boxes like you see from Travis-CI on pull requests, and it just gives me that deploy URL.  I've added you to the admin list on netlify, though not sure if that will generate the preview urls for you.  

Anyway, I'll go ahead and merge, this is all a bit of a work in progress anyway and this is a small edit.

**Pull request merged**
